# config.yaml

# ============================
# Directory Configuration
# ============================
directories:
  uploads: 'uploads'
  converted: 'converted'
  output: 'output'
  logs: 'logs'
  original_syllabus_dir: 'syllabus_data/originals'
  converted_syllabus_dir: 'syllabus_data/converted'
  parsed_syllabus_dir: 'syllabus_data/parsed'
  main_data_dir: 'syllabus_data/main'
  main_index_dir: 'syllabus_data/main'

# ============================
# Flask Configuration
# ============================
flask:
  debug: True
  host: '0.0.0.0'
  port: 5000
  secret_key: 'development_secret_key_should_be_changed_in_production'

# ============================
# File Settings
# ============================
file_settings:
  allowed_extensions:
    - 'pdf'
    - 'docx'
    - 'txt'
    - 'html'
    - 'htm'
  max_content_length: 16777216  # 16 MB

# ============================
# Logging Configuration
# ============================
logging:
  level: 'DEBUG'
  format: '%(asctime)s - %(name)s - %(levelname)s - [%(funcName)s:%(lineno)d] %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

# ============================
# Required Fields for Missing Fields Page (class_data)
# These fields, if missing after initial extraction, WILL trigger a user prompt.
# ============================
required_fields:
  - 'Time Zone'
  - 'Class Start Date'
  - 'Class End Date'
  - 'Days of Week'
  - 'Class Time'
  - 'Course Code'
  - 'Course Title'
  # Fields NOT listed here but present in the LLM extraction schema (like 'Term', 'Instructor Name', 'Term Start Date', 'Term End Date')
  # will be extracted if found by the LLM, but the user will NOT be prompted for them if they are missing.

# ============================
# Environment Variables to check
# ============================
environment_variables:
  - 'OPENAI_API_KEY'

# ============================
# Parser Specific Configurations
# ============================
openai_parser:
  max_chars_for_metadata: 30000
  max_api_retries: 2
  client_timeout:
    read: 60.0
    connect: 10.0

schedule_parser:
  default_term_weeks: 15

# ============================
# OpenAI Configuration
# ============================
openai:
  model: 'gpt-4.1-nano'
  api_key: null # Relies on environment variable OPENAI_API_KEY

# ============================
# Extraction Configuration
# ============================
extraction:
  openai_model: 'gpt-4.1-nano'
  openai_api_key: null # Relies on environment variable